name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v5
    
    - name: Install uv
      uses: astral-sh/setup-uv@v6
      with:
        version: "latest"
    
    - name: Set up Python
      uses: actions/setup-python@v6
      with:
        python-version: "3.9"
    
    - name: Install dependencies
      run: uv sync --dev
    
    - name: Run tests
      run: |
        mkdir -p data
        sqlite3 data/articles.db << 'EOF'
        CREATE TABLE articles (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            title TEXT,
            link TEXT UNIQUE,
            published TEXT,
            summary TEXT,
            embedded INTEGER DEFAULT 0,
            detected_language TEXT DEFAULT 'unknown',
            original_summary TEXT,
            is_translated INTEGER DEFAULT 0
        );
        INSERT INTO articles (title, link, published, summary) VALUES 
        ('Test Article 1', 'https://example.com/1', '2025-06-15T10:00:00+09:00', 'Test summary 1'),
        ('Test Article 2', 'https://example.com/2', '2025-06-15T11:00:00+09:00', 'Test summary 2'),
        ('Test Article 3', 'https://example.com/3', '2025-06-15T12:00:00+09:00', 'Test summary 3');
        EOF
        uv run python db_migration.py
        uv run python test_read_system.py
    
    - name: Build package
      run: uv build
    
    - name: Create Release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        draft: false
        prerelease: false